FROM node:8

WORKDIR /project/certificate/event

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

CMD npm install && npm start
